/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import config2.KoneksiDB;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.*;


/**
 *
 * @author y
 */
public class FormProdi extends javax.swing.JFrame {

    /**
     * Creates new form FormProdi
     */
    private Statement st;
    private ResultSet rs;
    private Connection conn;
    private String idProdiToUpdate;
    
    private void clearForm() {
        TFidjurusan.setText("");
        TFnamajurusan.setText("");
    }
    
    private void deleteDataProdi(String idProdi) throws SQLException {
        String queryDelete = "DELETE FROM tbl_prodi WHERE id_prodi = ?";

        try (PreparedStatement preparedStatement = conn.prepareStatement(queryDelete)) {
            preparedStatement.setString(1, idProdi);

            preparedStatement.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data Prodi berhasil dihapus.");
        }
    }
    
    private void tampilData() {
    DefaultTableModel kolomtabel = new DefaultTableModel();
    kolomtabel.addColumn("No.");
    kolomtabel.addColumn("ID Prodi");
    kolomtabel.addColumn("Prodi");
    try {
        int nomor = 1;
        // buat objek statement untuk mengeksekusi query mysql.
        st = conn.createStatement();
        // buat query ke database
        String sql = "SELECT * FROM tbl_prodi";
        // eksekusi query dan simpan hasilnya di objek ResultSet
        rs = st.executeQuery(sql);
        // tampilkan hasil query menggunakan perulangan while
        while (rs.next()) {
            kolomtabel.addRow(new Object[]{
                ("" + nomor++),
                rs.getString("id_prodi"),
                rs.getString("prodi")
            });
            tabel_prodi.setModel(kolomtabel);
            tabel_prodi.enable(true);
            TFnamajurusan.requestFocus();
        }
            tabel_prodi.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = tabel_prodi.rowAtPoint(evt.getPoint());
                idProdiToUpdate = tabel_prodi.getValueAt(row, 1).toString();
                TFidjurusan.setText(idProdiToUpdate);
                TFnamajurusan.setText(tabel_prodi.getValueAt(row, 2).toString());
            }
        });
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal menampilkan data. \n" + e.getMessage());
    }
}

    
public FormProdi() {
        initComponents();
        conn = KoneksiDB.getConnection();
        tampilData(); // Menampilkan data saat form diinisialisasi
        // Tambahkan inisialisasi atau konfigurasi lainnya jika diperlukan
    }

    // Metode atau logika lainnya dapat ditambahkan di sini


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TFidjurusan = new javax.swing.JTextField();
        TFnamajurusan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_prodi = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Form Prodi");

        jLabel2.setText("ID Prodi");

        jLabel3.setText("Nama Prodi");

        TFidjurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFidjurusanActionPerformed(evt);
            }
        });

        TFnamajurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFnamajurusanActionPerformed(evt);
            }
        });

        tabel_prodi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel_prodi);

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(btnTambah, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TFnamajurusan, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                .addComponent(TFidjurusan))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnUbah)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapus)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClear)
                        .addGap(31, 31, 31)
                        .addComponent(btnKembali)
                        .addGap(94, 94, 94)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFidjurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TFnamajurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTambah)
                            .addComponent(btnUbah)
                            .addComponent(btnHapus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnKembali)
                            .addComponent(btnClear)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int selectedRow = tabel_prodi.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih baris yang akan dihapus.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus data ini?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            String idProdi = tabel_prodi.getValueAt(selectedRow, 1).toString();

            try {
                deleteDataProdi(idProdi);
                tampilData(); // Refresh tampilan tabel setelah dihapus
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Gagal menghapus data Prodi. \n" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        try {
            String idJurusan = TFidjurusan.getText();
            String namaJurusan = TFnamajurusan.getText();

            // Validasi input
            if (idJurusan.isEmpty() || namaJurusan.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Isi semua field!");
                return;
            }

            // Buat objek statement untuk mengeksekusi query SQL
            st = conn.createStatement();

            // Buat query untuk menambahkan data ke tabel
            String sql = "INSERT INTO tbl_prodi (id_prodi, prodi) VALUES ('" + idJurusan + "', '" + namaJurusan + "')";

            // Eksekusi query
            st.executeUpdate(sql);

            // Tampilkan pesan berhasil
            JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan");

            // Refresh tampilan tabel
            tampilData();

            // Kosongkan field setelah tambah data
            TFidjurusan.setText("");
            TFnamajurusan.setText("");

        } catch (SQLException e) {
            // Tangani kesalahan SQL
            JOptionPane.showMessageDialog(this, "Gagal menambahkan data. \n" + e.getMessage());
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        if (idProdiToUpdate == null || idProdiToUpdate.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih data yang akan diubah!");
            return;
        }

        try {
            // Buat query untuk update data
            String sql = "UPDATE tbl_prodi SET prodi=? WHERE id_prodi=?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, TFnamajurusan.getText());
            ps.setString(2, idProdiToUpdate);

            // Eksekusi query update
            int hasil = ps.executeUpdate();

            // Tampilkan pesan sukses
            if (hasil > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil diubah");
                tampilData();
                clearForm();
            } else {
                JOptionPane.showMessageDialog(this, "Data tidak ditemukan");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        FormBiodata formBiodata = new FormBiodata();
        formBiodata.setVisible(true);
        this.dispose(); // Menutup form jurusan
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void TFidjurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFidjurusanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFidjurusanActionPerformed

    private void TFnamajurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFnamajurusanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFnamajurusanActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        TFidjurusan.setText("");
        TFnamajurusan.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void tabel_prodiMouseClicked(java.awt.event.MouseEvent evt) {
        int row = tabel_prodi.getSelectedRow();
        TFidjurusan.setText(tabel_prodi.getValueAt(row, 1).toString());
        TFnamajurusan.setText(tabel_prodi.getValueAt(row, 2).toString());
        // Set nilai ID Prodi yang akan diubah
        idProdiToUpdate = tabel_prodi.getValueAt(row, 1).toString();
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormProdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormProdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormProdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormProdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormProdi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TFidjurusan;
    private javax.swing.JTextField TFnamajurusan;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_prodi;
    // End of variables declaration//GEN-END:variables
}
